### ISSUE TITLE
hamshield.setFrequency will not compile

### ISSUE THREAD

**Issue by AF6TF** [EnhancedRadioDevices/HamShield#19]
a few of the example sketches use this call to the library. Each time I would compile this line would be called out with an error.  Even though this is defined in the hamshield.cpp, I had to change the sketch to use hamshield.frequency (440000) and that would compile and work.

**Comment by mogar** [comment]
setFrequency is a private method used by the frequency method. By calling frequency, you can make sure that the hardware sets itself up in the correct order and do basic error checking.

We've changed the examples so they call frequency instead of setFrequency(). Thanks for letting us know about this.
